name: YOLOv8Demo
options: { minimumXcodeGenVersion: 2.36.0, deploymentTarget: { iOS: "16.0" } }
targets:
  YOLOv8Demo:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.yolov8demo
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.10
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.2
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
